"""Turn channel hits and annotator output into schema-shaped evidence records."""

_PHROG_TOOL = "pharokka_phrog"
_PHOLD_TOOL = "phold_prostt5"


def _direction(product, rules):
    """Compound titles take the conservative reading.

    Third occurrence of one failure mode, so the rule is now applied here too:
      * N136 CDS0100  "collectin, c-type lectin"      -> the alignment was collagen
      * T4 P03739     "tail fiber assembly protein"   -> a chaperone, not a fibre
      * T5 CDS_0017   "endonuclease nicking abasic sites generated by host uracil
                       glycosylase Ung"               -> a DNA repair enzyme

    The last one reached the PRIMARY SET: `glycosyl` matched inside `glycosylase`,
    and direction_precedence checked receptor-binding before non-RBP identity, so
    a DNA repair enzyme was read as glycan-active. When a product names a positive
    RBP term AND a non-RBP identity, the non-RBP reading wins; when it names a
    positive term and a structural one, the structural reading wins.
    """
    dm = rules.get("stage4.direction_map")
    matched = {}
    for bucket in rules.get("stage4.direction_precedence"):
        hits = [t for t in dm.get(bucket, [])
                if str(t).lower() in (product or "").lower()]
        if hits:
            matched[bucket] = hits

    if not matched:
        return dm.get("_default", "uninformative")

    # An explicit receptor-binding claim is not a compound-title accident. RefSeq
    # calls N4 gp65 "tail sheath and receptor binding protein"; demoting that to
    # structural_only would make a genuine dual role unrepresentable.
    explicit = rules.get("stage4.explicit_rbp_terms", [])
    if any(str(e).lower() in (product or "").lower() for e in explicit):
        return "supports_receptor_binding"

    rb = "supports_receptor_binding"
    if rb in matched and len(matched) > 1:
        for conservative in ("supports_non_rbp_identity", "supports_structural_only"):
            if conservative in matched:
                return conservative
    for bucket in rules.get("stage4.direction_precedence"):
        if bucket in matched:
            return bucket
    return dm.get("_default", "uninformative")


def _strength(conf, rules):
    cm = rules.get("stage4.confidence_map")
    return cm.get(conf, cm.get("_default"))


def _full_region(rec):
    return {"start_aa": 1, "end_aa": max(rec["length_aa"], 1), "source": "manual"}


def _hit_region(rec):
    if rec.get("qstart") and rec.get("qend"):
        return {
            "start_aa": max(int(rec["qstart"]), 1),
            "end_aa": max(int(rec["qend"]), 1),
            "source": "foldseek_hit_span",
        }
    return _full_region(rec)


def build(rec, channels, rules, c2_matches, c5_details=None):
    """Return the evidence records for one CDS."""
    out = []
    full = _full_region(rec)

    ctx = {
        "C1": ("c1_module_position", "sits inside the C1 tail-module window"),
        "C3": ("c3_dark_matter", "unannotated CDS inside the tail-module window"),
        "C4": ("c4_tandem_cluster", "member of a nominated tandem cluster"),
        # Stage 6 recoveries are genomic-context evidence too, but their provenance is
        # kept distinct so a Stage 1 recall failure stays visible in the output.
        "S6-A1": ("s6_a1_module_sweep",
                  "tail-module CDS recovered by completeness audit A1"),
        "S6-A3": ("s6_a3_neighbourhood",
                  "flank of an assigned RBP recovered by completeness audit A3"),
    }
    for ch in ("C1", "C3", "C4", "S6-A1", "S6-A3"):
        if ch in channels:
            tool, note = ctx[ch]
            out.append({
                "family": "G",
                "tool": tool,
                "region": dict(full),
                "direction": "supports_apparatus_membership",
                "strength": "moderate",
                "raw": {"hit_description": note},
            })

    # --- family C, comparative genomics -------------------------------------
    # ONE record whether the CDS arrived through the C5 channel or was reopened by
    # completeness audit A4: both are the same datum -- this CDS sits in a locus that
    # is variable against a conserved backbone -- and evidence_families counts families,
    # never tools. The direction is capped at apparatus membership by the YAML;
    # "fast-evolving in relatives" is not "binds the receptor".
    if ("C5" in channels or "S6-A4" in channels) and c5_details:
        d = c5_details.get(rec["cds_id"]) or {}
        base = "stage1.channels.C5_comparative_variable_locus.evidence"
        direction = rules.get(base + ".direction")
        forbidden = rules.get(base + ".forbidden_direction")
        if direction == forbidden:                       # guard the rule, not the value
            raise ValueError("C5 direction must not be %s" % forbidden)
        via = "S6-A4" if "S6-A4" in channels and "C5" not in channels else "C5"
        out.append({
            "family": "C",
            "tool": "c5_comparative_variable_locus",
            "region": dict(full),
            "direction": direction,
            "strength": rules.get(base + ".strength"),
            "raw": {"hit_description":
                    "variable against a conserved backbone (%s, %s): ortholog present in "
                    "%s of the cohort at %s%% mean identity, %s pp against the flanking "
                    "neighbourhood (present in %s)"
                    % (via, d.get("signal"), d.get("self_presence"),
                       d.get("mean_identity_pct"), d.get("identity_drop_pp"),
                       d.get("flank_presence"))},
        })

    if "C2" in channels:
        hits = c2_matches.get(rec["cds_id"], {}).get("terms", [])
        out.append({
            "family": "G",
            "tool": "c2_keywords",
            "region": dict(full),
            "direction": _direction(rec["product"], rules),
            "strength": "weak",
            "raw": {"hit_description": "keyword(s) in product: " + ", ".join(hits)},
        })

    has_annotation = rec.get("phrog") is not None or rec["annotation_method"] != "none"
    if has_annotation:
        is_foldseek = rec["annotation_method"] == "foldseek"
        tool = _PHOLD_TOOL if is_foldseek else _PHROG_TOOL
        raw = {"hit_description": rec["product"]}
        if rec.get("tophit_protein"):
            raw["hit_id"] = rec["tophit_protein"]
        for src, dst in (("evalue", "evalue"), ("bitscore", "score")):
            if rec.get(src) is not None:
                raw[dst] = rec[src]
        if rec.get("fident") is not None:
            raw["identity_pct"] = round(rec["fident"] * 100, 1)
        out.append({
            "family": "D",
            "tool": tool,
            "region": _hit_region(rec) if is_foldseek else dict(full),
            "direction": _direction(rec["product"], rules),
            "strength": _strength(rec["annotation_confidence"], rules),
            "raw": raw,
        })

    return out
